spring:
  application:
    name: leave-service

  datasource:
    url: jdbc:postgresql://localhost:5433/leave_db
    username: leave_user
    password: leave_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

server:
  port: 8082

# Employee Service URL for inter-service communication
employee-service:
  url: http://localhost:8081
