services:
  # ── Employee Service Database ──
  employee-db:
    image: postgres:16-alpine
    container_name: employee-db
    environment:
      POSTGRES_DB: employee_db
      POSTGRES_USER: employee_user
      POSTGRES_PASSWORD: employee_pass
    ports:
      - "5432:5432"
    volumes:
      - employee-db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U employee_user -d employee_db" ]
      interval: 5s
      timeout: 5s
      retries: 5

  # ── Leave Service Database ──
  leave-db:
    image: postgres:16-alpine
    container_name: leave-db
    environment:
      POSTGRES_DB: leave_db
      POSTGRES_USER: leave_user
      POSTGRES_PASSWORD: leave_pass
    ports:
      - "5433:5432"
    volumes:
      - leave-db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U leave_user -d leave_db" ]
      interval: 5s
      timeout: 5s
      retries: 5
    # ── pgAdmin ──
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - employee-db
      - leave-db
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  employee-db-data:
  leave-db-data:
  pgadmin-data:
